### ISSUE TITLE
filter too restrictive with fixes

### ISSUE THREAD

**Issue by FabienArcellier** [BenJoyenConseil/github_insights#3]
A release on `writer/writer-framework` contains fixes and features. The graph that is displayed is disappointing when releases that contain a fix are excluded.

Without the filter (`src/index.md`)
```
annotations: re.map(
              (d) => ({date: d.d_date, text: d.version, href: `https://github.com/${gh_info.gh_organization}/${gh_info.gh_repo}/releases/${d.version}`})
            )
```
![Pasted image 20241123154951](https://github.com/user-attachments/assets/75444e1c-3222-4296-9085-ee34f5ca3755)

With the filter (`src/index.md`)
```
annotations: re.filter(
              (d) => (!d.has_fix)
            ).map(
              (d) => ({date: d.d_date, text: d.version, href: `https://github.com/${gh_info.gh_organization}/${gh_info.gh_repo}/releases/${d.version}`})
            )
```
![Pasted image 20241123155204](https://github.com/user-attachments/assets/e4fe7024-f2b6-4879-910d-31ae2f7cd8ba)

I am not sure about what to propose on this one. I suppose you set the filter for a reason.

**Comment by BenJoyenConseil** [comment]
I have removed the filter, you were right it was a quick fix that no longer has purpose
